/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminController;
import controller.SenderController;
import controller.StaffController;
import javax.swing.JOptionPane;
import model.Admin;
import model.Sender;
import model.Staff;

/**
 *
 * @author Admin
 */
public class DangNhap extends javax.swing.JFrame {
    SenderController senderController;
    AdminController adminController;
    StaffController staffController;
    
    private String Data;
    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        senderController  = new SenderController();
        adminController = new AdminController();
        staffController = new StaffController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbt_DangNhap_for_DangNhap = new javax.swing.JButton();
        Button_DKy_for_DangNhap = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        radio_jbt_Admin = new javax.swing.JRadioButton();
        radio_jbt_NhanVien = new javax.swing.JRadioButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Đăng Nhập");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nhập Tài Khoản");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nhập Mật Khẩu");

        jbt_DangNhap_for_DangNhap.setBackground(new java.awt.Color(51, 102, 255));
        jbt_DangNhap_for_DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbt_DangNhap_for_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        jbt_DangNhap_for_DangNhap.setText("Đăng Nhập");
        jbt_DangNhap_for_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_DangNhap_for_DangNhapActionPerformed(evt);
            }
        });

        Button_DKy_for_DangNhap.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Button_DKy_for_DangNhap.setText("Đăng Ký");
        Button_DKy_for_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DKy_for_DangNhapActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton3.setText("Quên Mật Khẩu?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Role:");

        buttonGroup1.add(radio_jbt_Admin);
        radio_jbt_Admin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        radio_jbt_Admin.setText("Admin");
        radio_jbt_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_jbt_AdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_jbt_NhanVien);
        radio_jbt_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        radio_jbt_NhanVien.setText("Nhân Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtUser)
                            .addComponent(jbt_DangNhap_for_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_DKy_for_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(radio_jbt_Admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radio_jbt_NhanVien)
                                .addGap(19, 19, 19))
                            .addComponent(txtPassword))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbt_DangNhap_for_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radio_jbt_Admin)
                    .addComponent(radio_jbt_NhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_DKy_for_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 300, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/font/AnhnenDangnhap.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed
    
    private void Button_DKy_for_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DKy_for_DangNhapActionPerformed
        // TODO add your handling code here:
        DangKy dangKy = new DangKy();
        dangKy.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Button_DKy_for_DangNhapActionPerformed

    private void jbt_DangNhap_for_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_DangNhap_for_DangNhapActionPerformed
        // TODO add your handling code here:
        String checkTk;
        
        if(radio_jbt_Admin.isSelected()){
           
            checkTk ="admin";
        }else if(radio_jbt_NhanVien.isSelected()){
            checkTk ="nhanvien";
        }else{
            checkTk ="nguoigui";
        }
        
        switch (checkTk) {
            case "admin":
                try {
                
            
                 String user = txtUser.getText();
                 if(txtUser.getText().equals("")||txtPassword.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đủ Thông Tin");
                 }else{
                    
                     adminController.selectedAdminShortCTL(user);
                     Admin admin =new Admin();
                     admin.setUser(adminController.getAdmin().getUser());
                     admin.setPassword(adminController.getAdmin().getPassword());
                  
                    if(admin.getPassword().equals(txtPassword.getText())){
                       // JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công");
                       AdminView adminView = new AdminView();
                       adminView.setVisible(true);
                       this.setVisible(false);
                            
                    }else{
                        if(admin.getPassword().equals(txtPassword.getText())==false){
                            JOptionPane.showMessageDialog(this, "Mật Khẩu Không chính xác");
                        }else{
                            JOptionPane.showMessageDialog(this, "Số Điện thoại không tồn tại");
                        }
                        
                    }
                 }
                 } catch (Exception e) {
                     JOptionPane.showMessageDialog(this, "Tài Khoản Không tồn Tại");
            }
                break;
            case "nhanvien":
              try {
                
            
                String phoneNv = txtUser.getText();
                 if(txtUser.getText().equals("")||txtPassword.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đủ Thông Tin");
                 }else{
                    
                    staffController.selectedStaffShortCTL(phoneNv);
                    Staff staff = new Staff();
                    staff.setPhone(staffController.getStaff().getPhone());
                    staff.setPassword(staffController.getStaff().getPassword());
                    
                    
                    
                    //cdsfghj
                    if(staff.getPassword().equals(txtPassword.getText())){
                        StaffView staffView = new StaffView();
                        staffView.setVisible(true);
                        this.setVisible(false);
                            
                    }else{
                        if(staff.getPassword().equals(txtPassword.getText())==false){
                            JOptionPane.showMessageDialog(this, "Mật Khẩu Không chính xác");
                        }else{
                            JOptionPane.showMessageDialog(this, "Số Điện thoại không tồn tại");
                        }
                        
                    }
                 }
                 } catch (Exception e) {
                     JOptionPane.showMessageDialog(this, "Tài Khoản Không tồn Tại");
            }
                break;
             case "nguoigui":
                 try {
                 
             
                 String phone = txtUser.getText();
                 
                 if(txtUser.getText().equals("")||txtPassword.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đủ Thông Tin");
                 }else{
                    
                    senderController.selectedSenderShortPhoneCTL(phone);
                    Sender sender = new Sender();
                    sender.setPhone(senderController.getSender().getPhone());
                    sender.setPassword( senderController.getSender().getPassword());
                    
                    if(sender.getPhone().equals(txtUser.getText())){
                       // JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công");
                       if(sender.getPassword().equals(txtPassword.getText())==false){
                            JOptionPane.showMessageDialog(this, "Mật Khẩu Không chính xác");
                        }else{
                            SenderView senderView = new SenderView(sender.getPhone());
                           // senderView.setData(sender.getPhone()+"gg");
                           //System.out.println(senderView.getData());
                            senderView.setVisible(true);
                            this.setVisible(false);
                        }
                           
                        }else{
                        
                         JOptionPane.showMessageDialog(this, "Số Điện thoại không tồn tại");
                    }
                 }
                 } catch (Exception e) {
                     JOptionPane.showMessageDialog(this, "Tài Khoản Không tồn Tại");
             }
                break;
            default:
                throw new AssertionError();
        }

    }//GEN-LAST:event_jbt_DangNhap_for_DangNhapActionPerformed

    private void radio_jbt_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_jbt_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_jbt_AdminActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        QuenMatKhau quenMatKhau = new QuenMatKhau();
        quenMatKhau.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    public String getData() {
        return Data;
    }

    public void setData(String Data) {
        this.Data = Data;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_DKy_for_DangNhap;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbt_DangNhap_for_DangNhap;
    private javax.swing.JRadioButton radio_jbt_Admin;
    private javax.swing.JRadioButton radio_jbt_NhanVien;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
