/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.StaffController;
import controller.TicketController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Staff;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVienJPanel extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form QuanLyNhanVienJPanel
     */
    StaffController staffController;
    public QuanLyNhanVienJPanel() {
        initComponents();
        
        staffController = new StaffController();
        
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        staffTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Id");
        defaultTableModel.addColumn("Full_Name");
        defaultTableModel.addColumn("Gender");
        defaultTableModel.addColumn("Age");
        defaultTableModel.addColumn("Phone");
        defaultTableModel.addColumn("PassWord");
        defaultTableModel.addColumn("Wage");
        
        List<Staff> staffs = staffController.getAllStaff();
        
        for(Staff staff : staffs){
            defaultTableModel.addRow(new Object[]{staff.getId(),
                staff.getFull_name(),staff.getGender(),staff.getAge(),
                staff.getPhone(),staff.getPassword(),staff.getWage() });
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtInsert = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jbtThemTk = new javax.swing.JButton();
        jbtXoaTk = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jcbGioiTinh = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(675, 414));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Quản Lý Nhân Viên");

        jbtSearch.setText("Tìm Kiếm");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập Số Điện Thoại:");

        jLabel3.setText("Tên Nhân Viên:");

        jLabel4.setText("Lương");

        jLabel5.setText("Số Điện Thoại");

        jLabel6.setText("Password:");

        jLabel7.setText("Giới Tính:");

        jLabel8.setText("Tuổi:");

        jbtThemTk.setText("Thêm Tài khoản");
        jbtThemTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemTkActionPerformed(evt);
            }
        });

        jbtXoaTk.setText("Xóa Tài Khoản");
        jbtXoaTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaTkActionPerformed(evt);
            }
        });

        jButton5.setText("Cập Nhật Tài Khoản");

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(staffTable);

        jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtSearch)))
                        .addGap(0, 186, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtTenNhanVien)
                            .addComponent(jcbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbtThemTk)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jbtXoaTk)
                                .addGap(37, 37, 37)
                                .addComponent(jButton5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPassword)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                            .addComponent(txtAge))))
                                .addGap(74, 74, 74))))))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtThemTk)
                    .addComponent(jButton5)
                    .addComponent(jbtXoaTk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtThemTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemTkActionPerformed
        // TODO add your handling code here:
        try{
        String t = String.valueOf(jcbGioiTinh.getSelectedItem());
        Staff staff = new Staff();
        
        staff.setFull_name(txtTenNhanVien.getText());
        staff.setGender(t);
        staff.setAge(txtAge.getText());
        staff.setPhone(txtPhone.getText());
        staff.setPassword(txtPassword.getText());
        staff.setWage(txtLuong.getText());
        StaffController staffcontroller = new StaffController();
        staffcontroller.addStaffCTL(staff);
        int h = staffcontroller.getCtlAdd();
        if(h != 0){
            JOptionPane.showMessageDialog(this, "Thêm nhân viên Thành Công!");
        }else{
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại!");
        }
        }catch(Exception  e){
           e.printStackTrace();
        }
        
        defaultTableModel.setRowCount(0);
        //them du lieu
        List<Staff> staffs1 = staffController.getAllStaff();
        
        for(Staff staff0 : staffs1){
          
            defaultTableModel.addRow(new Object[]{staff0.getId(),
                staff0.getFull_name(),staff0.getGender(),staff0.getAge(),
                staff0.getPhone(),staff0.getPassword(),staff0.getWage() });
        
        }
    }//GEN-LAST:event_jbtThemTkActionPerformed

    private void jbtXoaTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaTkActionPerformed
        // TODO add your handling code here:
        String ttt = txtInsert.getText();
        StaffController staffController = new StaffController();
        staffController.deleteStaffCTL(ttt);
       
        if(staffController.getRsDelete()==1){
            JOptionPane.showMessageDialog(this, "Xóa Tài Khoản Thành Công");
        }else{
            JOptionPane.showMessageDialog(this, "Xóa Tài Khoản Thất Bại");
        }
        
        txtInsert.setText("");
        txtAge.setText("");
        txtLuong.setText("");
        txtPassword.setText("");
        txtPhone.setText("");
        txtTenNhanVien.setText("");
        jcbGioiTinh.setSelectedItem("Nam");
                
                
        //cap nhat lai bang
        defaultTableModel.setRowCount(0);
        //them du lieu
        List<Staff> staffs1 = staffController.getAllStaff();
        
        for(Staff staff0 : staffs1){
          
            defaultTableModel.addRow(new Object[]{staff0.getId(),
                staff0.getFull_name(),staff0.getGender(),staff0.getAge(),
                staff0.getPhone(),staff0.getPassword(),staff0.getWage() });
        
        }
    }//GEN-LAST:event_jbtXoaTkActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        // TODO add your handling code here:
        
        StaffController staffController = new StaffController();
        staffController.selectedStaffCTL(txtInsert.getText());
        Staff staff = new Staff();
        staff = staffController.getStaff();
        txtTenNhanVien.setText(staff.getFull_name());
        txtLuong.setText(staff.getWage());
        jcbGioiTinh.setSelectedItem(staff.getGender());
        txtPhone.setText(staff.getPhone());
        txtAge.setText(staff.getAge());
                
    }//GEN-LAST:event_jbtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtThemTk;
    private javax.swing.JButton jbtXoaTk;
    private javax.swing.JComboBox<String> jcbGioiTinh;
    private javax.swing.JTable staffTable;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtInsert;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
