/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.SenderController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sender;


/**
 *
 * @author Admin
 */
public class QuanLyNguoiGuiJPanel extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel;
    SenderController senderController;
    /**
     * Creates new form QuanLyNguoiGuiJPanel
     */
    public QuanLyNguoiGuiJPanel() {
        initComponents();
        senderController = new SenderController();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        
       };
       
       senderTable.setModel(defaultTableModel);
       
       defaultTableModel.addColumn("Id");
       defaultTableModel.addColumn("Full_name");
       defaultTableModel.addColumn("Gender");
       defaultTableModel.addColumn("Age");
       defaultTableModel.addColumn("Phone");
       defaultTableModel.addColumn("Password");
       defaultTableModel.addColumn("License_Plate");
       
       List<Sender> senders = senderController.getAllSenderCTL();
        
       
        for(Sender sender : senders){
            defaultTableModel.addRow(new Object[]{sender.getId(),
            sender.getFull_name(), sender.getGender(), sender.getAge(),
            sender.getPhone(), sender.getPassword(), sender.getLicense_Plate() });
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInsertPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jcbGioiTinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtLicense_plate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtSoluongNguoiGui = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        senderTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Người Gửi");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 6, -1, -1));

        jLabel2.setText("Nhập Số Điện Thoại:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 40, -1, -1));

        txtInsertPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertPhoneActionPerformed(evt);
            }
        });
        add(txtInsertPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 37, 148, -1));

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 37, -1, -1));

        jLabel3.setText("Tên Người Gửi:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 73, -1, -1));

        jLabel4.setText("Tuổi:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 109, -1, -1));

        jLabel5.setText("Giới Tính:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 140, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 143, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 143, -1));

        jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        add(jcbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 143, -1));

        jLabel6.setText("Số Điện Thoại:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel7.setText("Password:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel8.setText("Biển Số Xe:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 140, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 140, -1));
        add(txtLicense_plate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 140, -1));

        jButton2.setText("Làm Mới");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 177, -1, -1));

        jButton3.setText("Xóa Người Gửi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 177, -1, -1));

        jButton4.setText("Cập Nhật Người Gửi");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 177, -1, -1));

        jLabel9.setText("Số Lượng Người Gửi:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 215, -1, -1));
        add(txtSoluongNguoiGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 60, -1));

        senderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(senderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 250, 670, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsertPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertPhoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SenderController senderController = new SenderController();
        senderController.selectedSenderShortPhoneCTL(txtInsertPhone.getText());
        txtAge.setText(senderController.getSender().getAge());
        txtLicense_plate.setText(senderController.getSender().getLicense_Plate());
        txtName.setText(senderController.getSender().getFull_name());
        txtPassword.setText(senderController.getSender().getPassword());
        txtPhone.setText(senderController.getSender().getPhone());
        jcbGioiTinh.setSelectedItem(senderController.getSender().getGender());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    SenderController senderController = new SenderController();
    senderController.deleteSenderCTL(txtInsertPhone.getText());
    if(senderController.getRsDelete()!=0){
        JOptionPane.showMessageDialog(this, "Xóa Thành Công");
    }else{
        JOptionPane.showMessageDialog(this, "Xóa Thất Bại");
    }
    
    defaultTableModel.setRowCount(0);
    List<Sender> senders = senderController.getAllSenderCTL();
        
       
        for(Sender sender : senders){
            defaultTableModel.addRow(new Object[]{sender.getId(),
            sender.getFull_name(), sender.getGender(), sender.getAge(),
            sender.getPhone(), sender.getPassword(), sender.getLicense_Plate() });
        }  
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbGioiTinh;
    private javax.swing.JTable senderTable;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtInsertPhone;
    private javax.swing.JTextField txtLicense_plate;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSoluongNguoiGui;
    // End of variables declaration//GEN-END:variables
}
